#!/usr/bin/env python3

import telegram
from telegramlogger import default_token_path
from pathlib import Path
import argparse

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Send Telegram messages.')
    parser.add_argument('--tokenfile', '-t', nargs=1, default=default_token_path,
                        help=f'file containing the telegram token (default: {default_token_path})')
    parser.add_argument('--get-updates', '-u', action='store_true',
                        help='get messages recently sent to the bot')

    args = parser.parse_args()

    bot = None
    with open(args.tokenfile, 'r') as f:
        token = f.read().strip()
        bot = telegram.Bot(token=token)

    if args.get_updates:
        updates = bot.get_updates()
        for update in updates:
            msg = update.message
            print(f'{msg.chat.last_name}, {msg.chat.first_name} ({msg.chat_id}): "{msg.text}"')
    else:
        parser.print_help()
